import { PrismaNeon } from '@prisma/adapter-neon';
// Generated by Prisma's new "prisma-client" generator (Prisma 7+, see
// prisma/schema.prisma) — this client has no native/WASM query engine to
// load from disk, which is what made every query crash on Cloudflare
// Workers ("[unenv] fs.readdir is not implemented yet!"). It runs as plain
// JS and works on both Workers and Node.js.
import { PrismaClient } from '@/lib/generated/prisma/client';

// Prisma 7's PrismaNeon adapter takes the connection string directly and
// manages its own connection internally — no need to construct a
// @neondatabase/serverless Pool (or configure a WebSocket constructor)
// ourselves anymore.
const connectionString = `${process.env.DATABASE_URL}`;
const adapter = new PrismaNeon({ connectionString });

export const prisma = new PrismaClient({ adapter });