// Generated by Prisma's new "prisma-client" generator (Prisma 7+, see
// prisma/schema.prisma) — this client has no native/WASM query engine to
// load from disk, which is what made every query crash on Cloudflare
// Workers ("[unenv] fs.readdir is not implemented yet!"). It runs as plain
// JS and works on both Workers and Node.js.
import { PrismaClient } from '@/lib/generated/prisma/client';
// IMPORTANT: PrismaNeonHttp, not PrismaNeon. `prisma` below is a module-level
// singleton, reused across every request the Worker handles. PrismaNeon
// (the WebSocket/Pool-based adapter) opens one persistent socket the first
// time it's used and keeps reusing it — but Cloudflare Workers ties I/O
// objects to the request that created them, so the *next* request to reuse
// that socket crashes with "Cannot perform I/O on behalf of a different
// request" / "Connection terminated". PrismaNeonHttp issues each query as
// its own independent fetch() call instead, with no connection held open
// between requests, which is safe for a singleton client on Workers. This
// project doesn't use interactive prisma.$transaction(), so the one
// capability the HTTP driver can't do (multi-step interactive transactions)
// isn't needed here.
import { PrismaNeonHttp } from '@prisma/adapter-neon';

const connectionString = `${process.env.DATABASE_URL}`;
const adapter = new PrismaNeonHttp(connectionString, {});

export const prisma = new PrismaClient({ adapter });