// Generated by Prisma's new "prisma-client" generator (Prisma 7+, see
// prisma/schema.prisma) — this client has no native/WASM query engine to
// load from disk, which is what made every query crash on Cloudflare
// Workers ("[unenv] fs.readdir is not implemented yet!"). It runs as plain
// JS and works on both Workers and Node.js.
import { PrismaClient } from '@/lib/generated/prisma/client';
// PrismaNeon (WebSocket/Pool-based), not PrismaNeonHttp — nested writes
// like prisma.order.create({ data: { items: { create: [...] } } }) (used
// at checkout, and for products with images in the admin) run as an
// implicit multi-statement transaction under the hood, and Neon's HTTP
// adapter flatly can't do that: "Transactions are not supported in HTTP
// mode". The WebSocket adapter can. See the comment on getClient below
// for why a fresh Pool per request (not a shared one) is what makes this
// safe on Workers.
import { PrismaNeon } from '@prisma/adapter-neon';
import { cache } from 'react';

// Cloudflare Workers ties every I/O object (sockets, streams, and some of
// what a Prisma driver adapter holds internally too) to the specific
// request that created it. A PrismaClient built once at module scope and
// reused across every request throws on the second request to touch it:
//   Error: Cannot perform I/O on behalf of a different request.
// We first tried Neon's HTTP adapter (stateless fetch per query) to avoid
// that — it worked, but broke nested writes ("Transactions are not
// supported in HTTP mode"), since Neon's HTTP driver can't run
// multi-statement transactions at all.
// The actual fix: keep the WebSocket adapter (so transactions work), but
// never share a client (or its underlying Pool/socket) across requests —
// build one fresh per request instead, via React's cache() (same
// primitive lib/settings.ts already uses for exactly this reason).
const getClient = cache(() => {
  const connectionString = `${process.env.DATABASE_URL}`;
  const adapter = new PrismaNeon({ connectionString });
  return new PrismaClient({ adapter });
});

// A thin proxy so every existing call site (import { prisma } from
// "@/lib/db", then prisma.product.findMany() etc.) keeps working
// unchanged — each property access resolves to the current request's
// client via getClient() above, instead of one client shared forever.
export const prisma: PrismaClient = new Proxy({} as PrismaClient, {
  get(_target, prop, receiver) {
    const client = getClient();
    const value = Reflect.get(client as object, prop, receiver);
    // Top-level methods like prisma.$disconnect() are called as
    // (this proxy).$disconnect(), which would bind `this` to the proxy
    // itself rather than the real client — bind explicitly so it's
    // always the real instance. Model delegates (prisma.setting) are
    // plain objects, not functions, so they pass through untouched.
    return typeof value === "function" ? value.bind(client) : value;
  },
}) as PrismaClient;
